### ISSUE TITLE
Update token name

### ISSUE THREAD

**Issue by RooTender** [sonarsource-cfamily-examples/windows-msbuild-gh-actions-sc#13]
Hi!
I've been trying to install the Sonarcloud for like 2-3 days basing on this repository. It seems that the configuration here differs from the original setup.
No problem with that, but for new people like me it might be hard to notice that **the tokens name are different the the ones in the documentation (and tutorial)**. I know it's only a small change, but it takes quite a lot to find it out (the logs aren't that helpful)

Could you rename the token name from `SONARCLOUD_TOKEN` to `SONAR_TOKEN` in the .yml file?

File here:
![image](https://user-images.githubusercontent.com/24989290/181061416-ae52213b-e7e1-4206-99d9-54fb74d7844c.png)

Docs:
![image](https://user-images.githubusercontent.com/24989290/181061516-4e2e5ed0-8387-4903-b6ea-e880a1720a5a.png)

**Comment by amelie-renard-sonarsource** [comment]
Hello @RooTender,

I am sorry to read that the name of this token got in your way.

Unfortunately, we cannot use `SONAR_TOKEN` because we need two distinct tokens: `SONARCLOUD_TOKEN` and `SONARQUBE_TOKEN`. And with our current organization, it would be tough for us to have only one name.

What we can do, though, is to
- update the README of the examples so that they mention the correct token name instead of `SONAR_TOKEN` (and emphasize the fact that the name is different from the one in the documentation)
- add a comment about it where the token is used.

Do you think that would be enough?

Thank you

**Comment by amelie-renard-sonarsource** [comment]
Modifications are done
